export const CHAT_LANGUAGES = [
  { id: 'en', label: 'English', flag: '🇬🇧' },
  { id: 'ar', label: 'Arabic', flag: '🇦🇪' },
  { id: 'hi', label: 'Hindi', flag: '🇮🇳' },
  { id: 'ur', label: 'Urdu', flag: '🇵🇰' },
  { id: 'ps', label: 'Pashto', flag: '🇦🇫' },
  { id: 'bn', label: 'Bengali', flag: '🇧🇩' },
  { id: 'fa', label: 'Farsi (Persian)', flag: '🇮🇷' },
  { id: 'ml', label: 'Malayalam', flag: '🇮🇳' },
  { id: 'ta', label: 'Tamil', flag: '🇮🇳' },
  { id: 'kn', label: 'Kannada', flag: '🇮🇳' },
  { id: 'te', label: 'Telugu', flag: '🇮🇳' },
  { id: 'mr', label: 'Marathi', flag: '🇮🇳' },
  { id: 'gu', label: 'Gujarati', flag: '🇮🇳' },
  { id: 'pa', label: 'Punjabi', flag: '🇮🇳' },
  { id: 'pah', label: 'Pahadi', flag: '🇮🇳' },
  { id: 'zh', label: 'Chinese (Mandarin)', flag: '🇨🇳' },
  { id: 'ja', label: 'Japanese', flag: '🇯🇵' },
  { id: 'ko', label: 'Korean', flag: '🇰🇷' },
  { id: 'th', label: 'Thai', flag: '🇹🇭' },
  { id: 'my', label: 'Burmese', flag: '🇲🇲' },
  { id: 'ms', label: 'Malay', flag: '🇲🇾' },
  { id: 'tl', label: 'Tagalog', flag: '🇵🇭' },
  { id: 'id', label: 'Indonesian', flag: '🇮🇩' },
  { id: 'tr', label: 'Turkish', flag: '🇹🇷' },
  { id: 'fr', label: 'French', flag: '🇫🇷' },
  { id: 'es', label: 'Spanish', flag: '🇪🇸' },
  { id: 'ru', label: 'Russian', flag: '🇷🇺' },
  { id: 'ku', label: 'Kurdish', flag: '🇮🇶' },
  { id: 'ne', label: 'Nepali', flag: '🇳🇵' },
  { id: 'si', label: 'Sinhala', flag: '🇱🇰' }
];

export const AGENT_LANGUAGES = [
  { id: 'en', label: 'English' },
  { id: 'hi', label: 'Hindi' },
  { id: 'ur', label: 'Urdu' },
  { id: 'ps', label: 'Pashto' },
  { id: 'ar', label: 'Arabic' },
  { id: 'pa', label: 'Punjabi' },
  { id: 'ta', label: 'Tamil' },
  { id: 'pah', label: 'Pahadi' },
  { id: 'zh', label: 'Chinese' },
  { id: 'ja', label: 'Japanese' },
  { id: 'ko', label: 'Korean' },
  { id: 'th', label: 'Thai' },
  { id: 'my', label: 'Burmese' },
  { id: 'ms', label: 'Malay' },
  { id: 'ml', label: 'Malayalam' },
  { id: 'fr', label: 'French' },
  { id: 'es', label: 'Spanish' },
  { id: 'bn', label: 'Bengali' },
  { id: 'fa', label: 'Farsi' }
];
